name: Frontend build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    name: Deploy frontend
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd /home/vavasto/frontend/Tiflo.com--Frontend && git pull
      - name: Build containers
        uses: appleboy/ssh-action@master
        with:
          timeout: 10m
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd /home/vavasto/frontend/Tiflo.com--Frontend && npm install && sudo docker build . -t frontend && sudo docker run -v /home/vavasto/frontend/public/dist:/app/dist -t frontend
